spring:

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-root.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  application:
    name: user-work

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crm
    shema: application
    username: postgres
    password: 7403663


server:
  port: 8080