spring:
  cloud:
    compatibility-verifier:
      enabled: false

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true

server:
  port: 8083

feign:
  httpclient:
    connection-timeout: 5000

